In [1]:
#Import the libraries

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
#Loading the Dataset

In [4]:
data=pd.read_csv('C:/Users/USER/OneDrive/Desktop/ICT/Datas/Sales_add.csv')

In [5]:
data

Month      Region      Manager  Sales_before_digital_add(in $)  \
0    Month-1  Region - A  Manager - A                          132921   
1    Month-2  Region - A  Manager - C                          149559   
2    Month-3  Region - B  Manager - A                          146278   
3    Month-4  Region - B  Manager - B                          152167   
4    Month-5  Region - C  Manager - B                          159525   
5    Month-6  Region - A  Manager - B                          137163   
6    Month-7  Region - C  Manager - C                          130625   
7    Month-8  Region - A  Manager - A                          131140   
8    Month-9  Region - B  Manager - C                          171259   
9   Month-10  Region - C  Manager - B                          141956   
10  Month-11  Region - B  Manager - C                          159339   
11  Month-12  Region - A  Manager - A                          178939   
12  Month-13  Region - B  Manager - A                          145062   
13  Month-14  Region - A  Manager - A                          151514   
14  Month-15  Region - C  Manager - A                          147463   
15  Month-16  Region - A  Manager - B                          177195   
16  Month-17  Region - A  Manager - C                          140862   
17  Month-18  Region - C  Manager - B                          167996   
18  Month-19  Region - B  Manager - A                          132135   
19  Month-20  Region - A  Manager - B                          152493   
20  Month-21  Region - B  Manager - A                          147425   
21  Month-22  Region - A  Manager - C                          130263   

    Sales_After_digital_add(in $)  
0                          270390  
1                          223334  
2                          244243  
3                          231808  
4                          258402  
5                          256948  
6                          222106  
7                          230637  
8                          226261  
9                          193735  
10                         203175  
11                         276279  
12                         205180  
13                         253131  
14                         229336  
15                         187305  
16                         234908  
17                         191517  
18                         227040  
19                         212579  
20                         263388  
21                         243020

In [6]:
data.describe()

Sales_before_digital_add(in $)  Sales_After_digital_add(in $)
count                       22.000000                      22.000000
mean                    149239.954545                  231123.727273
std                      14844.042921                   25556.777061
min                     130263.000000                  187305.000000
25%                     138087.750000                  214960.750000
50%                     147444.000000                  229986.500000
75%                     157627.500000                  250909.000000
max                     178939.000000                  276279.000000

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 5 columns):
 #   Column                          Non-Null Count  Dtype 
---  ------                          --------------  ----- 
 0   Month                           22 non-null     object
 1   Region                          22 non-null     object
 2   Manager                         22 non-null     object
 3   Sales_before_digital_add(in $)  22 non-null     int64 
 4   Sales_After_digital_add(in $)   22 non-null     int64 
dtypes: int64(2), object(3)
memory usage: 1008.0+ bytes


# The company wishes to clarify whether there is any increase in sales after stepping into digital marketing.


In [8]:
#Null Hypothesis,H0: There is no increase in sales after stepping into digital marketting.
#Alternative Hypothesis,H1: There is increase in sales after stepping into digital marketting.

In [9]:
data[['Sales_before_digital_add(in $)','Sales_After_digital_add(in $)']]

Sales_before_digital_add(in $)  Sales_After_digital_add(in $)
0                           132921                         270390
1                           149559                         223334
2                           146278                         244243
3                           152167                         231808
4                           159525                         258402
5                           137163                         256948
6                           130625                         222106
7                           131140                         230637
8                           171259                         226261
9                           141956                         193735
10                          159339                         203175
11                          178939                         276279
12                          145062                         205180
13                          151514                         253131
14                          147463                         229336
15                          177195                         187305
16                          140862                         234908
17                          167996                         191517
18                          132135                         227040
19                          152493                         212579
20                          147425                         263388
21                          130263                         243020

In [10]:
#Testing statistically to see if the data is normally distributed.

In [11]:
from scipy import stats as sts

In [12]:
sts.shapiro(data['Sales_before_digital_add(in $)'])

ShapiroResult(statistic=0.9306764006614685, pvalue=0.12674309313297272)

In [13]:
sts.shapiro(data['Sales_After_digital_add(in $)'])

ShapiroResult(statistic=0.9702128767967224, pvalue=0.7159645557403564)

In [14]:
#Conducting paired sample t-test

In [15]:
ttest,pval=sts.ttest_rel(data['Sales_After_digital_add(in $)'],data['Sales_before_digital_add(in $)'],alternative='greater')

In [16]:
ttest,pval

(12.09070525287017, 3.168333502287889e-11)

In [17]:
t_critic=sts.t.ppf(q=0.05/2,df=22)

In [18]:
t_critic

-2.073873067904015

In [19]:
if(ttest>t_critic and pval<0.05):
    print('We are rejecting null hypothesis\nThere is increase in sales after stepping into digital marketting')
else:
    print('We fail to reject null hypothesis\nThere is no increase in sales after stepping into digital marketting')

We are rejecting null hypothesis
There is increase in sales after stepping into digital marketting


# The company needs to check whether there is any dependency between the features “Region” and “Manager”.

In [20]:
contingency_table=pd.crosstab(data["Region"],data["Manager"])
print('contingency_table :-\n',contingency_table)

contingency_table :-
 Manager     Manager - A  Manager - B  Manager - C
Region                                           
Region - A            4            3            3
Region - B            4            1            2
Region - C            1            3            1


In [21]:
#Observed Values
Observed_Values = contingency_table.values 
print("Observed Values :-\n",Observed_Values)

Observed Values :-
 [[4 3 3]
 [4 1 2]
 [1 3 1]]


In [22]:
b=sts.chi2_contingency(contingency_table)
Expected_Values = b[3]
print("Expected Values :-\n",Expected_Values)

Expected Values :-
 [[4.09090909 3.18181818 2.72727273]
 [2.86363636 2.22727273 1.90909091]
 [2.04545455 1.59090909 1.36363636]]


In [23]:
no_of_rows=len(contingency_table.iloc[0:2,0])
no_of_columns=len(contingency_table.iloc[0,0:2])
ddof=(no_of_rows-1)*(no_of_columns-1)
print("Degree of Freedom:-",ddof)
alpha = 0.05

Degree of Freedom:- 1


In [24]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(Observed_Values,Expected_Values)])
chi_square_statistic=chi_square[0]+chi_square[1]
print("chi-square statistic:-",chi_square_statistic)

chi-square statistic:- 2.921995464852608


In [25]:
critical_value=chi2.ppf(q=1-alpha,df=ddof)
print('critical_value:',critical_value)

critical_value: 3.841458820694124


In [26]:
#p-value
p_value=1-chi2.cdf(x=chi_square_statistic,df=ddof)
print('p-value:',p_value)

p-value: 0.08737974495299139


In [27]:
print('Significance level: ',alpha)
print('Degree of Freedom: ',ddof)
print('chi-square statistic:',chi_square_statistic)
print('critical_value:',critical_value)
print('p-value:',p_value)

Significance level:  0.05
Degree of Freedom:  1
chi-square statistic: 2.921995464852608
critical_value: 3.841458820694124
p-value: 0.08737974495299139


In [28]:
if (chi_square_statistic>=critical_value and p_value<=alpha):
    print("Reject null hypothesis \n There is a relationship between 2 categorical variables")
else:
    print("Failed to reject null hypothesis \n There is no relationship between 2 categorical variables")

Failed to reject null hypothesis 
 There is no relationship between 2 categorical variables
